eureka:
  environment: ${environment:local}
  datacenter: ${dataCenter:localhost}
  enableSelfPreservation: false
  server:
    eviction-interval-timer-in-ms: 1000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${peerUrls:http://localhost:${port:8761}/eureka}
      # fix this to get peerUrls instead get java.net.URISyntaxException: Illegal character in path at index 1: ${peerUrls}/
  instance:
    hostname: ${hostName:localhost}
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

endpoints:
  shutdown:
    enabled: true