ribbon-for-stockService-v1:
  ribbon:
    # Eureka vipAddress of the target service
    DeploymentContextBasedVipAddresses: stockService
    #listOfServers: localhost:${SERVER.PORT}
    ListOfServers: localhost:8761
    # Interval to refresh the server list from the source (ms)
    ServerListRefreshInterval: 30000

# same service but with different endpoint
ribbon-for-stockService-v2:
  ribbon:
    # Eureka vipAddress of the target service
    DeploymentContextBasedVipAddresses: stockService
    #listOfServers: localhost:${SERVER.PORT}
    ListOfServers: localhost:8761
    # Interval to refresh the server list from the source (ms)
    ServerListRefreshInterval: 30000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${serviceDiscoveryPath?:http://localhost:8761/eureka/}
  instance:
    hostname: ${hostName:localhost}
    statusPageUrlPath: ${server.servlet-path}/info
    healthCheckUrlPath: ${server.servlet-path}/health
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}